### ISSUE TITLE
Box Webdav Deprecation

### ISSUE THREAD

**Issue by AlroneRhyn** [buttercup/datasources#6]
Hi !

Box webdav support will be deprecated in January 2019 => https://community.box.com/t5/Box-Product-News/Deprecation-WebDAV-Support/ba-p/55684

Do you have any plan to use box api instead ?

Thx a lot !

**Comment by perry-mitchell** [comment]
We integrated the webdav connection for Box but never went through with a full release. I think we'd definitely benefit from having it out, so yes I think we could take a look at the API.

**Comment by perry-mitchell** [comment]
For now I think we'll remove Box - we can add support for it when we have more bandwidth, or if someone chooses to add support for it.
